// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHWM5rwdAxKj8ISTUntGVyy6Ij8iF4Q40',
    appId: '1:773562056780:web:38199fca6bff739377b4e9',
    messagingSenderId: '773562056780',
    projectId: 'fitness-b1d73',
    authDomain: 'fitness-b1d73.firebaseapp.com',
    storageBucket: 'fitness-b1d73.firebasestorage.app',
    measurementId: 'G-J2KJFBWH21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU5RqCI_zeHS7DDf-WqX2C5Q6pXmm-4zA',
    appId: '1:773562056780:android:5f65166cd0ddf5ad77b4e9',
    messagingSenderId: '773562056780',
    projectId: 'fitness-b1d73',
    storageBucket: 'fitness-b1d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6IYMmCDAGp45wsgBVhzoiRqgdMMaU48',
    appId: '1:773562056780:ios:a254f665db0f262b77b4e9',
    messagingSenderId: '773562056780',
    projectId: 'fitness-b1d73',
    storageBucket: 'fitness-b1d73.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6IYMmCDAGp45wsgBVhzoiRqgdMMaU48',
    appId: '1:773562056780:ios:a254f665db0f262b77b4e9',
    messagingSenderId: '773562056780',
    projectId: 'fitness-b1d73',
    storageBucket: 'fitness-b1d73.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHWM5rwdAxKj8ISTUntGVyy6Ij8iF4Q40',
    appId: '1:773562056780:web:5346398a3ff69a6977b4e9',
    messagingSenderId: '773562056780',
    projectId: 'fitness-b1d73',
    authDomain: 'fitness-b1d73.firebaseapp.com',
    storageBucket: 'fitness-b1d73.firebasestorage.app',
    measurementId: 'G-KG3PCR449E',
  );
}
